dist: trusty  # note rabbitmq is currently not available on xenial
language: python
sudo: required
cache: pip

services:
- postgresql
- rabbitmq

addons:
  postgresql: "10.6"

matrix:
  include:
    - python: 3.6
      env: TEST_TYPE="pre-commit"
    - python: 3.6
      env: TEST_TYPE="pytest" TEST_AIIDA_BACKEND="django" PYPI_DEPLOY=true
    - python: 2.7
      env: TEST_TYPE="pytest" TEST_AIIDA_BACKEND="django"
    - python: 3.6
      env: TEST_TYPE="pytest" TEST_AIIDA_BACKEND="sqlalchemy"

  allow_failures:
    - env: TEST_TYPE="code-style"

before_install:

  # This installs a relatively old version of LAMMPS (11 Nov 2013)
  - if [[ "$TEST_TYPE" == "pytest" ]]; then sudo apt-get update -q; fi
  - if [[ "$TEST_TYPE" == "pytest" ]]; then sudo apt-get install lammps -y; fi

# Ideally we would want to run this, however, they are only built for debian-xenial not trusty
#  - sudo add-apt-repository ppa:gladky-anton/lammps -y
#  - sudo apt-get update -q
#  - sudo apt-get install lammps-stable -y

# This would be a more complex (and time consuming route)
#- git clone -b stable_22Aug2018 https://github.com/lammps/lammps.git lammps
#- cd lammps/src
#- make serial
#- ls
#- cd ../..

# get version of lammps
#  - if [[ "$TEST_TYPE" == "pytest" ]]; then lammps -h || true; fi

install:
- pip install -U pip wheel setuptools "reentry>=1.3"
- pip install numpy==1.16.4 # otherwise numpy 1.17 is installed, which is incompatible with aiida-core==1.0.0b5
- |
    if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install typing==3.6.6 # otherwise importlib_resources installs incompatible version for aiida-core==1.0.0b5
    fi
- |
    if [[ "$TEST_TYPE" == "pytest" ]]; then
      pip install -e .[testing]
      pip install coveralls
    fi
- |
    if [[ "$TEST_TYPE" == "pre-commit" ]]; then
      pip install -e .[code_style]
    fi

before_script:
- |
    if [[ "$TEST_TYPE" == "pytest" ]]; then
      reentry scan
    fi

script:
- |
  if [[ "$TEST_TYPE" == "pytest" ]]; then
      pytest -v --cov=aiida_lammps --cov-report= aiida_lammps
  fi
- |
  if [[ "$TEST_TYPE" == "pre-commit" ]]; then
    pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
  fi

# after_success:
# - coveralls

deploy:
  - provider: pypi
    distributions: "sdist bdist_wheel"
    user: cjsewell
    password:
      secure: NkYuJbR79czDGc//QknIQeCwi7IJUA9VHQ4WfZz1gaMk3lQljO7b8a6HPIcqNv6jSwuLc2uz3P0frIUTkxvNTmWFUwbYz/eTyCsuHb0znjqGslTmWv97+8DCtJIQ9fDFSd1ym1FDkvOwrNBUncIaApta8bmzsP6tOQOuiz+BcLhzMH8J91d8RRzw/MnUtKS20vP58cjVuz3Q9tondfVBC+i5F2MeXNU4tXL7p31dVvBPFwhfmJ1dJ/QJgnACmNz0BPHdrIq1iXH1B7oj4EtAdEil4BKGKBY8Ipg6nBpJvOlPXE6iKvltaih2EsWx9CZvT/oT1Rz8V1osZi1hc4aQ26SCIlAUo6ak5onCCayDMWLLPV7QuNf5E4edK+d3GBtkXCu9jWEVHEJW5XIhg/E45WN/FSvap6q4qyhWr3sCkwxTe1/OO3i09KuiQGD5w+a/9WSJ1gW31Iu5Sy77qWPdvdKhsuazGdx8sl1Wj99dLtrfJH88q+emXPRKNYFY6n8JecJC4CAyqxLih7Zc/WTFgG9gTEuC8OfriuHoWdNZIkcLdQMdrGZsoPYhD0dYz333so4eq56YTYYM1qSA2wh6BdJ1eXR/Fn/+mpRJyqIj7xYx/8FYwLr5qnWVh6HE5TstpRYqgJ1iL64Y1BTv6HWfcrK473SZuoah/21XOYXyQ+A=
    on:
      branch: master
      tags: true
      condition: $PYPI_DEPLOY = true
