language: python
python:
- "2.7"

cache: pip

services:
- postgresql
- rabbitmq  # required for aiida >= 1.0

addons:
  postgresql: "9.5"

env:
  matrix:
    - TEST_TYPE: tests
      TEST_AIIDA_BACKEND: django
    - TEST_TYPE: tests
      TEST_AIIDA_BACKEND: sqlalchemy
#    - TEST_TYPE: pre-commit
#    - TEST_TYPE: docs
#      READTHEDOCS: 'True'
    - TEST_TYPE="tests" AIIDA_BRANCH="develop" TEST_AIIDA_BACKEND="django"
    - TEST_TYPE="tests" AIIDA_BRANCH="develop" TEST_AIIDA_BACKEND="sqlalchemy"

matrix:
  allow_failures:
    - env: TEST_TYPE="tests" AIIDA_BRANCH="develop" TEST_AIIDA_BACKEND="django"
    - env: TEST_TYPE="tests" AIIDA_BRANCH="develop" TEST_AIIDA_BACKEND="sqlalchemy"

before_install:
#  - if [[ "$TEST_TYPE" == "tests" ]]; then sudo add-apt-repository ppa:gladky-anton/lammps -y; fi
  - if [[ "$TEST_TYPE" == "tests" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TEST_TYPE" == "tests" ]]; then sudo apt-get install apt-show-versions; fi
  - if [[ "$TEST_TYPE" == "tests" ]]; then sudo apt-show-versions lammps; fi
#  - if [[ "$TEST_TYPE" == "tests" ]]; then apt-cache search lammps; fi
  - if [[ "$TEST_TYPE" == "tests" ]]; then sudo apt-get install -y lammps; fi
  - if [[ "$TEST_TYPE" == "tests" ]]; then lammps -h; fi

install:
# Upgrade pip setuptools and wheel
- pip install -U pip wheel setuptools
- pip install -e .[testing]
- >
  if [[ ! -z "${AIIDA_BRANCH}" ]]; then
    cur_path="$(pwd)";
    cd ..;
    git clone --branch=${AIIDA_BRANCH} https://github.com/aiidateam/aiida_core.git;
    cd aiida_core;
    pip install -U .[testing];
    cd "$cur_path";
  fi
#- pip install coveralls

before_script:
- reentry scan

script:
- >
  if [[ "$TEST_TYPE" == "tests" ]]; then
    if [[ ! -z "${AIIDA_BRANCH}" ]]; then
      pytest -v aiida_lammps;
    else
      pytest -v aiida_lammps;
    fi
  fi
- >
  if [[ "$TEST_TYPE" == "pre-commit" ]]; then
  pre-commit install;
  pre-commit run --all-files || ( git status --short; git diff ; exit 1 ) ;
  fi
- if [[ "$TEST_TYPE" == "docs" ]]; then cd docs; make; fi

#after_success:
#- coveralls

